development:
  adapter: postgresql
  database: bookmarks_development
  username: root
  encoding: utf8
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: bookmarks_test
  pool: 5
  encoding: utf8
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: bookmarks_production
  pool: 5
  username: bookmarks
  password:
